version: '{branch}-{build}'
configuration: Release
clone_depth: 5
clone_folder: c:\stellarium
environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    platform: x64
    qtver: 5.9.5
    qtbin: msvc2017_64
    msvcname: Visual Studio 15 2017 Win64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    platform: x64
    qtver: 5.11.0
    qtbin: msvc2017_64
    msvcname: Visual Studio 15 2017 Win64
before_build:
- cmd: >-
    set PATH=C:\Qt\%qtver%\%qtbin%\bin;%PATH%

    cd c:\stellarium

    mkdir build-%qtver%-%qtbin% && cd build-%qtver%-%qtbin%

    cmake -DENABLE_TESTING=1 -G "%msvcname%" ..
build:
  project: c:\stellarium\build-%qtver%-%qtbin%\Stellarium.sln
  parallel: true
  verbosity: minimal
test_script:
- cmd: ctest --output-on-failure
