env:
  global:
   - secure: "nDBuoowqSmcjCOsK4uXfkRRGuvcLt434lXeZIND/bfOEDgOv7h62w5h4i3ebSgItWkBStLzGB8Owfb2v/S0jC+wSIoP+SD2wRg12LA0/eeb3OBYw/TR5FlCVx21/GzvODTNi8NdWb92AcYGhbLNPqMDIFHGscARjHiP2EnONhTs="

language: cpp

matrix:
  include:

    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
          update:
            - true
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - TRANSLATE=true

    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
          update:
            - true
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
        - TRANSLATE=false

    - os: osx
      osx_image: xcode9.3
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        - TRANSLATE=false

before_install:
  - eval "${MATRIX_EVAL}"
  # Linux
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      mkdir qt5;
      wget -q -O qt5.zip https://github.com/Stellarium/stellarium-data/releases/download/qt-5.6/qt5.zip;
      unzip -qq qt5.zip -d qt5;
      export PATH=`pwd`/qt5/bin:$PATH;
      export QT_PLUGIN_PATH=`pwd`/qt5/plugins;
    fi
  # Mac OS X
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update > /dev/null;
      brew upgrade > /dev/null;
      brew install qt;
      export PATH="/usr/local/opt/qt/bin:$PATH";
    fi

install:

before_script:
  - export DISPLAY=:99.0
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok )& fi
  - sleep 3 # give xvfb some time to start
  - mkdir build
  - cd build

script:
  - cmake -DENABLE_TESTING=1 ..
  - make -j5
  - ctest --output-on-failure

after_success:
  - if [[ "$TRANSLATE" == true && "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == false ]]; then
      pip install virtualenv;
      virtualenv ~/env;
      source ~/env/bin/activate;
      pip install transifex-client;
      sudo echo $'[https://www.transifex.com]\nhostname = https://www.transifex.com\nusername = '"$TRANSIFEX_USER"$'\npassword = '"$TRANSIFEX_PASSWORD"$'\ntoken = '"$TRANSIFEX_API_TOKEN"$'\n' > ~/.transifexrc;
      tx push -s;
    fi
